// Copyright 2021 Google LLC
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

//go:build generate
// +build generate

package main

import (
	"compress/flate"
	"crypto/sha256"
	"crypto/x509"
	"encoding/csv"
	"encoding/pem"
	"io"
	"log"
	"net/http"
	"os"
	"text/template"
	"time"
)

//go:generate go run generate.go

// ccadb is from https://wiki.mozilla.org/CA/Intermediate_Certificates.
const ccadb = "https://ccadb-public.secure.force.com/mozilla/MozillaIntermediateCertsCSVReport"

func main() {
	c := &http.Client{Timeout: 1 * time.Minute}
	req, err := c.Get(ccadb)
	fatalIfErr(err)
	defer req.Body.Close()
	if req.StatusCode != http.StatusOK {
		log.Fatalf("GET got %d: %v", req.StatusCode, req.Status)
	}

	text, err := os.Create("intermediates.pem")
	fatalIfErr(err)
	defer func() { fatalIfErr(text.Close()) }()
	zf, err := os.Create("intermediates.bin")
	fatalIfErr(err)
	defer func() { fatalIfErr(zf.Close()) }()
	zw, err := flate.NewWriter(zf, flate.DefaultCompression)
	fatalIfErr(err)
	defer func() { fatalIfErr(zw.Close()) }()

	count := 0
	seen := make(map[[sha256.Size]byte]bool)

	r := csv.NewReader(req.Body)
	header, err := r.Read()
	fatalIfErr(err)
	if header[4] != "PEM" {
		log.Fatal("Format changed.")
	}

	for {
		record, err := r.Read()
		if err == io.EOF {
			break
		}
		fatalIfErr(err)

		b, _ := pem.Decode([]byte(record[4]))
		if b == nil {
			log.Fatalf("Record is not valid PEM: %#v", record)
		}
		if _, err := x509.ParseCertificate(b.Bytes); err != nil {
			log.Printf("%#v", record)
			log.Fatalf("Invalid certificate: %v", err)
		}
		hash := sha256.Sum256(b.Bytes)
		if seen[hash] {
			log.Printf("Duplicate record: %v", record[0])
			continue
		}
		seen[hash] = true

		io.WriteString(text, "# Subject: "+record[0]+"\n")
		io.WriteString(text, "# Issuer: "+record[1]+"\n")
		io.WriteString(text, record[4])
		io.WriteString(text, "\n")
		io.WriteString(zw, record[4])
		io.WriteString(zw, "\n")
		count++
	}

	f, err := os.Create("count.go")
	fatalIfErr(err)
	defer func() { fatalIfErr(f.Close()) }()

	tmpl.Execute(f, count)

	log.Printf("Wrote %d intermediates.", count)
}

var tmpl = template.Must(template.New("count.go").Parse(
	`// Code generated by generate.go. DO NOT EDIT.

package intermediates

const expectedCount = {{ . }}
`))

func fatalIfErr(err error) {
	if err != nil {
		log.Panic(err)
	}
}
